package Crypt::NSS::Certificates;

use strict;
use warnings;

require Exporter;
our @ISA = qw(Exporter);

use constant {
    CERT_USAGE_SSL_CLIENT => 0,
    CERT_USAGE_SSL_SERVER => 1,
    CERT_USAGE_SSL_SERVERWITHSTEPUP => 2,
    CERT_USAGE_SSL_CA => 3,
    CERT_USAGE_EMAIL_SIGNER => 4,
    CERT_USAGE_EMAIL_RECIPIENT => 5,
    CERT_USAGE_OBJECT_SIGNER => 6,
    CERT_USAGE_USER_CERT_IMPORT => 7,
    CERT_USAGE_VERIFY_CA => 8,
    CERT_USAGE_PROTECTED_OBJECT_SIGNER => 9,
    CERT_USAGE_STATUS_RESPONDER => 10,
    CERT_USAGE_ANY_CA => 11,
};

our @EXPORT = qw();
our @EXPORT_OK = qw(
    CERT_USAGE_SSL_CLIENT
    CERT_USAGE_SSL_SERVER
    CERT_USAGE_SSL_SERVERWITHSTEPUP
    CERT_USAGE_SSL_CA
    CERT_USAGE_EMAIL_SIGNER
    CERT_USAGE_EMAIL_RECIPIENT
    CERT_USAGE_OBJECT_SIGNER
    CERT_USAGE_USER_CERT_IMPORT
    CERT_USAGE_VERIFY_CA
    CERT_USAGE_PROTECTED_OBJECT_SIGNER
    CERT_USAGE_STATUS_RESPONDER
    CERT_USAGE_ANY_CA
);

our %EXPORT_TAGS = (
    usage => [qw(
        CERT_USAGE_SSL_CLIENT
        CERT_USAGE_SSL_SERVER
        CERT_USAGE_SSL_SERVERWITHSTEPUP
        CERT_USAGE_SSL_CA
        CERT_USAGE_EMAIL_SIGNER
        CERT_USAGE_EMAIL_RECIPIENT
        CERT_USAGE_OBJECT_SIGNER
        CERT_USAGE_USER_CERT_IMPORT
        CERT_USAGE_VERIFY_CA
        CERT_USAGE_PROTECTED_OBJECT_SIGNER
        CERT_USAGE_STATUS_RESPONDER
        CERT_USAGE_ANY_CA
    )],
);

1;